import React, { useState } from "react";
import { useNavigate } from "react-router-dom";

import { preview } from "../assets";
import { getRandomPrompt } from "../utils";
import { FormField, Loader } from "../components";

const CreatePost = () => {
  const navigate = useNavigate();

  const [form, setForm] = useState({
    name: "",
    prompt: "",
    photo: "",
  });
  const [generatingImg, setGeneratingImg] = useState(false);
  const [loading, setLoading] = useState(false);

  const handleSubmit = () => {};
  const handleChange = (e) => {};
  const handleSupriseMe = () => {};

  return;
  <section className="max-w-7xl mwx-auto">
    <div>
      <h1 className="font-extrabold text-[#222328] text-[32px]">Create</h1>
      <p className="mt-3 text-[#666e75] text-[16px] max-w[500px]">
        Create imaginative and visually stunning images generated by-DELL-E AI
        and share with community
      </p>
    </div>
    <form className="mt-16 max-w-3xl" onSubmit={handleSubmit}>
      <div classNAme="flex flex-col gap-5">
        <FormField
          labelName="Your Name"
          type="text"
          name="name"
          palceolder="Lace"
          value={form.name}
          handleChange={handleChange}
        />
        <FormField
          labelName="Prompt"
          type="text"
          name="prompt"
          palceolder="A synthwave style sunset above the reflecting water of the sea, digital art"
          value={form.prompt}
          handleChange={handleChange}
          isSupriseMe
          handleSupriseMe={handleSupriseMe}
        />
        <div className="relative bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 w-64 p-3 h-64 flex justify-center items-center "></div>
      </div>
    </form>
  </section>;
};

export default CreatePost;
