import React, { useState, useEffect } from "react";
import { Loader, Card, FormField } from "../components";

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPost, setAllPost] = useState([null]);
  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]">
          The Community Showcase
        </h1>
        <p className="mt-3 text-[#666e75] text-[16px] max-w[500px]">
          Browser through a collection of imaginative and visually stunning
          images generated by-DELL-E AI
        </p>
      </div>
      <div className="mt-16">
        <FormField />
      </div>
    </section>
  );
};

export default Home;
